<form class="row" action="/product/add" method="post">
    <div class="col-12">
        <input type="text" name="name" placeholder="Enter Name">
    </div>
    <div class="col-12">
        <input type="number" name="price" placeholder="Enter Price">
    </div>
    <div class="col-12">
        <select name="type" id="type">
            <option value="Electronics">Electronics</option>
            <option value="Jewellery">Jewellery</option>
        </select>
    </div>
    <div class="col-12">
        <input type="number" name="quantity" placeholder="Enter Quantity">
    </div>
    <button class="btn btn-primary" type="submit">Add</button>
</form>